# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5oOs4ySg_3PQGcUo4DDMWLbC_WS4maR

#calculadora de notas
"""

#qual sua nota?
#pedindo a nota
nota = input  ("qual sua nota?")
nota2 = input ("qual sua nota?")
#transformando em numeros inteiros
nota = int(nota)
nota2 = int(nota2)
#media da nota
media = (nota + nota2)/2
print (f"sua media é: {media}")
#pontos extra
pontos_extra = input ("quantos pontos extra você tem?")
pontos_extra = int(pontos_extra)
#media final
media_final = media + pontos_extra
print (f"sua media final é: {media_final}")
if media_final >= 70:
  print("Parabéns, você passou!")
else:
  print("Estude mais!")
  faltou = 70 - media_final
  print(f"Faltou {faltou} pontos para passar.")